Repository php-llm/llm-chain, pull requests merged in 2024-12, with the labels that each got.

#151 [BC BREAK] Extend `VectorSearchInterface::query()` for a `$minScore`
  src/Bridge/Azure/Store/SearchStore.php
  src/Bridge/ChromaDB/Store.php
  src/Bridge/MongoDB/Store.php
  src/Bridge/Pinecone/Store.php
  src/Store/VectorStoreInterface.php
Labels: enhancement, BC BREAK

#150 Parse OpenAI response embedding to contain all embeddings
  src/Bridge/OpenAI/Embeddings/ResponseConverter.php
  tests/Bridge/OpenAI/Embeddings/ResponseConverterTest.php
Labels: OpenAI

#161 Handle `int`, `float`, `array`, `\Stringable` and `\JsonSerializable` return values from tools
  src/Chain/ToolBox/ToolBox.php
  tests/Chain/ToolBox/ToolBoxTest.php
  tests/Fixture/Tool/ToolReturningArray.php
  tests/Fixture/Tool/ToolReturningFloat.php
  tests/Fixture/Tool/ToolReturningInteger.php
  tests/Fixture/Tool/ToolReturningJsonSerializable.php
  tests/Fixture/Tool/ToolReturningStringable.php
Labels: enhancement

#158 Handle response errors
  src/Bridge/Anthropic/ModelHandler.php
  src/Bridge/Ollama/LlamaModelHandler.php
  src/Bridge/OpenAI/Embeddings/ResponseConverter.php
  src/Bridge/Replicate/LlamaResponseConverter.php
  src/Bridge/Voyage/ModelHandler.php
Labels: enhancement

#174 [BC BREAK] `MessageBag` does not depend on `\ArrayObject` anymore
  src/Bridge/Meta/LlamaPromptConverter.php
  src/Chain/ToolBox/ChainProcessor.php
  src/Model/Message/MessageBag.php
  tests/Bridge/Meta/LlamaPromptConverterTest.php
  tests/Model/Message/MessageBagTest.php
Labels: enhancement, BC BREAK
