Repository php-llm/llm-chain, pull requests merged in 2024-10, with the labels that each got.

#76 Change order of commands in `Makefile`
  Makefile
Labels: enhancement

#79 Filter out `Document`s without text in `DocumentEmbedder` + tests
  src/DocumentEmbedder.php
  tests/DocumentEmbedderTest.php
Labels: enhancement

#84 Use `symfony/clock` in `DocumentEmbedder`
  composer.json
  src/DocumentEmbedder.php
  tests/DocumentEmbedderTest.php
Labels: enhancement

#86 Add test for `ResponseFormatFactory`
  tests/StructuredOutput/ResponseFormatFactoryTest.php
Labels: enhancement

#75 Add ability to describe tool parameters via `#[ToolParameter]` attribute
  src/ToolBox/Attribute/ToolParameter.php
  src/ToolBox/ParameterAnalyzer.php
  tests/ToolBox/Attribute/ToolParameterTest.php
  tests/ToolBox/ParameterAnalyzerTest.php
  tests/ToolBox/Tool/ToolWithToolParameterAttribute.php
Labels: enhancement

#94 Clear exception hierachy
  src/Document/Vector.php
  src/Exception/DomainException.php
  src/Exception/ExceptionInterface.php
  src/Exception/InvalidArgumentException.php
  src/Exception/InvalidToolImplementation.php
  src/Exception/LogicException.php
  src/Exception/MessageBagNotFound.php
  src/Exception/MissingModelSupport.php
  src/Exception/RuntimeException.php
  src/OpenAI/Model/Gpt.php
  src/OpenAI/Platform/AbstractPlatform.php
  src/Response/Response.php
  src/Store/MongoDB/Store.php
  src/ToolBox/Tool/YouTubeTranscriber.php
  src/ToolBox/ToolBox.php
  tests/Response/ResponseTest.php
Labels: enhancement

#93 Introduce `ResponseFormatInterface`
  src/StructuredOutput/ChainProcessor.php
  src/StructuredOutput/ResponseFormatFactory.php
  src/StructuredOutput/ResponseFormatFactoryInterface.php
Labels: enhancement

#104 Rename `ContentInterface` to `Content`
  src/Message/Content/Content.php
  src/Message/Content/Image.php
  src/Message/Content/Text.php
  src/Message/Message.php
  src/Message/UserMessage.php
Labels: enhancement

#100 Simplify `SchemaFactory`
  examples/structured-output-math.php
  src/StructuredOutput/ResponseFormatFactory.php
  src/StructuredOutput/SchemaFactory.php
  tests/StructuredOutput/ResponseFormatFactoryTest.php
  tests/StructuredOutput/SchemaFactoryTest.php
Labels: enhancement

#102 Do not call `upsert()` with empty array
  src/Store/Pinecone/Store.php
Labels: bug

#103 No mocks in `DocumentsEmbedderTest`
  tests/DocumentEmbedderTest.php
  tests/Double/TestEmbeddingsModel.php
  tests/Double/TestStore.php
Labels: enhancement

#112 Use `#[\SensitiveParameter]`
  src/Anthropic/Platform/Anthropic.php
  src/OpenAI/Platform/Azure.php
  src/OpenAI/Platform/OpenAI.php
  src/Store/Azure/SearchStore.php
  src/Voyage/Platform/Voyage.php
Labels: enhancement

#110 refactor: split `Document` into `TextDocument` and `VectorDocument`
  examples/store-mongodb-similarity-search.php
  examples/store-pinecone-similarity-search.php
  src/Document/Document.php
  src/Document/TextDocument.php
  src/Document/VectorDocument.php
  src/DocumentEmbedder.php
  src/Store/Azure/SearchStore.php
  src/Store/ChromaDB/Store.php
  src/Store/MongoDB/Store.php
  src/Store/Pinecone/Store.php
  src/Store/StoreInterface.php
  src/Store/VectorStoreInterface.php
  src/ToolBox/Tool/SimilaritySearch.php
  tests/DocumentEmbedderTest.php
  tests/Double/TestStore.php
Labels: enhancement, BC BREAK

#114 Introduce `NullVector` and `VectorInterface`
  src/Document/NullVector.php
  src/Document/Vector.php
  src/Document/VectorDocument.php
  src/Document/VectorInterface.php
  src/Store/Azure/SearchStore.php
  tests/Document/NullVectorTest.php
  tests/Document/VectorTest.php
Labels: bug

#119 Revert "chore: remove reasoning example to safe my credit card (#116)"
  .env
  examples/reasoning-openai.php
Labels: enhancement

#117 refactor: `ResponseInterface` as `Chain` return value
  examples/chat-claude-anthropic.php
  examples/chat-gpt-azure.php
  examples/chat-gpt-openai.php
  examples/image-describer.php
  examples/reasoning-openai.php
  examples/store-mongodb-similarity-search.php
  examples/store-pinecone-similarity-search.php
  examples/stream-claude-anthropic.php
  examples/stream-gpt-openai.php
  examples/structured-output-math.php
  examples/toolbox-clock.php
  examples/toolbox-serpapi.php
  examples/toolbox-weather.php
  examples/toolbox-wikipedia.php
  examples/toolbox-youtube.php
  src/Anthropic/Model/Claude.php
  src/Chain.php
  src/OpenAI/Model/Gpt.php
  src/Response/ChoiceResponse.php
  src/Response/Response.php
  src/Response/ResponseInterface.php
  src/Response/StreamResponse.php
  src/Response/StructuredResponse.php
  src/Response/TextResponse.php
  src/Response/ToolCallResponse.php
  src/StructuredOutput/ChainProcessor.php
  src/ToolBox/ChainProcessor.php
  tests/Response/ChoiceResponseTest.php
  tests/Response/ResponseTest.php
  tests/Response/StreamResponseTest.php
  tests/Response/StructuredResponseTest.php
  tests/Response/TextResponseTest.php
  tests/Response/TollCallResponseTest.php
  tests/ToolBox/ChainProcessorTest.php
Labels: enhancement, BC BREAK

#118 feat: introduce chain awareness in chain processors to nest them
  examples/structured-output-clock.php
  src/Chain.php
  src/Chain/ChainAwareProcessor.php
  src/Chain/ChainAwareTrait.php
  src/Chain/Output.php
  src/Chain/OutputProcessor.php
  src/StructuredOutput/ChainProcessor.php
  src/ToolBox/ChainProcessor.php
  tests/StructuredOutput/ChainProcessorTest.php
Labels: enhancement

#127 Remove superflous header
  src/Anthropic/Platform/Anthropic.php
  src/OpenAI/Platform/Azure.php
  src/OpenAI/Platform/OpenAI.php
  src/Store/Azure/SearchStore.php
  src/Voyage/Platform/Voyage.php
Labels: enhancement

#128 [Anthropic] Make version configurable
  src/Anthropic/Platform/Anthropic.php
Labels: enhancement

#131 docs: rework readme to cover all features
  README.md
  examples/chat-o1-openai.php
Labels: documentation
