Repository php-llm/llm-chain, pull requests merged in 2025-06, with the labels that each got.

#327 refactor: chain aware with interface
  src/Chain/ChainAwareInterface.php
  src/Chain/ChainAwareTrait.php
Labels: refactor

#330 test: to mock the ChainInterface we need to skip broken PHPUnit versions
  composer.json
Labels: test

#345 docs: add MariaDB in readme
  README.md
Labels: documentation

#347 feat: Add Gemini Embeddings
  examples/store/mariadb-similarity-search-gemini.php
  src/Platform/Bridge/Google/Embeddings.php
  src/Platform/Bridge/Google/Embeddings/ModelClient.php
  src/Platform/Bridge/Google/Embeddings/TaskType.php
  src/Platform/Bridge/Google/PlatformFactory.php
  src/Platform/ModelClientInterface.php
  tests/Platform/Bridge/Google/Embeddings/EmbeddingsModelClientTest.php
Labels: feature

#357 fix: youtube tool in dev examples
  composer.json
Labels: bug

#358 feat: allow filtering down of examples in runner
  example
Labels: test

#208 feat: chat + message store
  composer.json
  examples/persistent-chat.php
  src/Chain/Chat.php
  src/Chain/Chat/MessageStore/CacheStore.php
  src/Chain/Chat/MessageStore/InMemoryStore.php
  src/Chain/Chat/MessageStore/SessionStore.php
  src/Chain/Chat/MessageStoreInterface.php
  src/Chain/ChatInterface.php
Labels: feature

#368 fix: resolve array tool arguments
  src/Chain/Toolbox/ToolCallArgumentResolver.php
  tests/Chain/Toolbox/ToolCallArgumentResolverTest.php
  tests/Fixture/Tool/ToolArray.php
Labels: bug
