Repository php-llm/llm-chain, pull requests merged in 2025-04, with the labels that each got.

#209 feat: add support for Anthropic tool use
  src/Bridge/Anthropic/Claude.php
  src/Bridge/Anthropic/ModelHandler.php
Labels: feature

#274 ci: update rector config for deprecations and skipping data provider …
  rector.php
Labels: CI/CD

#275 fix: toolbox usage in claude model handler after renaming
  src/Bridge/Anthropic/ModelHandler.php
Labels: bug

#272 fix: usage of Claude without system prompt
  examples/toolbox-wikipedia.php
  src/Bridge/Anthropic/ModelHandler.php
Labels: bug

#273 ci: reorder qa pipeline to shift commit check to last step
  .github/workflows/pipeline.yml
Labels: CI/CD

#276 feat: bring in Llama 3.3 support with Azure
  .env
  README.md
  examples/chat-llama-azure.php
  src/Bridge/Azure/Meta/LlamaHandler.php
  src/Bridge/Azure/Meta/PlatformFactory.php
  src/Bridge/Meta/Llama.php
Labels: feature

#277 feat: add latest Claude model versions
  examples/chat-claude-anthropic.php
  src/Bridge/Anthropic/Claude.php
Labels: feature

#281 ci: skip mongodb extension for now
  .github/workflows/pipeline.yml
Labels: CI/CD

#278 refactor: rename Model::version to Model::name
  examples/chat-claude-anthropic.php
  examples/chat-llama-azure.php
  examples/image-generator-dall-e-3.php
  src/Bridge/Anthropic/Claude.php
  src/Bridge/Anthropic/ModelHandler.php
  src/Bridge/Azure/Meta/LlamaHandler.php
  src/Bridge/Azure/OpenAI/EmbeddingsModelClient.php
  src/Bridge/Azure/OpenAI/GPTModelClient.php
  src/Bridge/Azure/OpenAI/WhisperModelClient.php
  src/Bridge/Google/Gemini.php
  src/Bridge/Google/ModelHandler.php
  src/Bridge/Meta/Llama.php
  src/Bridge/Ollama/LlamaModelHandler.php
  src/Bridge/OpenAI/DallE.php
  src/Bridge/OpenAI/DallE/ModelClient.php
  src/Bridge/OpenAI/Embeddings.php
  src/Bridge/OpenAI/Embeddings/ModelClient.php
  src/Bridge/OpenAI/GPT.php
  src/Bridge/OpenAI/GPT/ModelClient.php
  src/Bridge/OpenAI/Whisper.php
  src/Bridge/OpenAI/Whisper/ModelClient.php
  src/Bridge/OpenRouter/Client.php
  src/Bridge/OpenRouter/GenericModel.php
  src/Bridge/Replicate/LlamaModelClient.php
  src/Bridge/Voyage/ModelHandler.php
  src/Bridge/Voyage/Voyage.php
  src/Model/Model.php
  tests/Bridge/OpenAI/DallETest.php
Labels: BC BREAK, refactor

#284 feat: allow access of methods and read of properties through AsyncRes…
  examples/image-generator-dall-e-3.php
  src/Model/Response/AsyncResponse.php
Labels: feature

#283 refactor: add more output to example runner
  example
Labels: refactor

#279 feat: add support for Hugging Face Inference API
  .env
  Makefile
  README.md
  examples/huggingface/_model-listing.php
  examples/huggingface/audio-classification.php
  examples/huggingface/automatic-speech-recognition.php
  examples/huggingface/chat-completion.php
  examples/huggingface/feature-extraction.php
  examples/huggingface/fill-mask.php
  examples/huggingface/image-classification.php
  examples/huggingface/image-segmentation.php
  examples/huggingface/image-to-text.php
  examples/huggingface/object-detection.php
  examples/huggingface/question-answering.php
  examples/huggingface/sentence-similarity.php
  examples/huggingface/summarization.php
  examples/huggingface/table-question-answering.php
  examples/huggingface/text-classification.php
  examples/huggingface/text-generation.php
  examples/huggingface/text-to-image.php
  examples/huggingface/token-classification.php
  examples/huggingface/translation.php
  examples/huggingface/zero-shot-classification.php
  huggingface
  src/Bridge/HuggingFace/ApiClient.php
  src/Bridge/HuggingFace/Model.php
  src/Bridge/HuggingFace/ModelClient.php
  src/Bridge/HuggingFace/Output/Classification.php
  src/Bridge/HuggingFace/Output/ClassificationResult.php
  src/Bridge/HuggingFace/Output/DetectedObject.php
  src/Bridge/HuggingFace/Output/FillMaskResult.php
  src/Bridge/HuggingFace/Output/ImageSegment.php
  src/Bridge/HuggingFace/Output/ImageSegmentationResult.php
  src/Bridge/HuggingFace/Output/MaskFill.php
  src/Bridge/HuggingFace/Output/ObjectDetectionResult.php
  src/Bridge/HuggingFace/Output/QuestionAnsweringResult.php
  src/Bridge/HuggingFace/Output/SentenceSimilarityResult.php
  src/Bridge/HuggingFace/Output/TableQuestionAnsweringResult.php
  src/Bridge/HuggingFace/Output/Token.php
  src/Bridge/HuggingFace/Output/TokenClassificationResult.php
  src/Bridge/HuggingFace/Output/ZeroShotClassificationResult.php
  src/Bridge/HuggingFace/PlatformFactory.php
  src/Bridge/HuggingFace/Provider.php
  src/Bridge/HuggingFace/ResponseConverter.php
  src/Bridge/HuggingFace/Task.php
  src/Model/Response/BinaryResponse.php
  tests/Bridge/HuggingFace/ModelClientTest.php
Labels: feature

#280 feat: add support for TransformersPHP for model runtime in PHP
  .gitignore
  README.md
  composer.json
  examples/transformers-text-generation.php
  src/Bridge/TransformersPHP/Handler.php
  src/Bridge/TransformersPHP/Model.php
  src/Bridge/TransformersPHP/PipelineResponse.php
  src/Bridge/TransformersPHP/PlatformFactory.php
Labels: feature

#287 chore: updating some composer metadata + normalize
  composer.json
Labels: chore

#289 test: fix namespaces and coverage
  tests/Bridge/Google/GooglePromptConverterTest.php
  tests/Bridge/HuggingFace/ModelClientTest.php
  tests/Bridge/Meta/LlamaPromptConverterTest.php
  tests/Model/Message/Content/ImageTest.php
Labels: test

#270 feat: Add Raw Response Metadata Handling - GPT Token Usage Example
  examples/chat-gpt-openai-metadata.php
  src/Bridge/OpenAI/DallE/ImageResponse.php
  src/Bridge/OpenAI/TokenOutputProcessor.php
  src/Chain/Toolbox/StreamResponse.php
  src/Model/Response/AsyncResponse.php
  src/Model/Response/BaseResponse.php
  src/Model/Response/BinaryResponse.php
  src/Model/Response/ChoiceResponse.php
  src/Model/Response/Exception/RawResponseAlreadySet.php
  src/Model/Response/Metadata/Metadata.php
  src/Model/Response/Metadata/MetadataAwareTrait.php
  src/Model/Response/RawResponseAwareTrait.php
  src/Model/Response/ResponseInterface.php
  src/Model/Response/StreamResponse.php
  src/Model/Response/StructuredResponse.php
  src/Model/Response/TextResponse.php
  src/Model/Response/ToolCallResponse.php
  src/Model/Response/VectorResponse.php
  tests/Bridge/OpenAI/TokenOutputProcessorTest.php
  tests/Model/Response/AsyncResponseTest.php
  tests/Model/Response/BaseResponseTest.php
  tests/Model/Response/Exception/RawResponseAlreadySetTest.php
  tests/Model/Response/Metadata/MetadataAwareTraitTest.php
  tests/Model/Response/Metadata/MetadataTest.php
  tests/Model/Response/RawResponseAwareTraitTest.php
Labels: feature

#293 refactor: use lib specific exceptions instead of native ones
  src/Bridge/HuggingFace/ModelClient.php
  src/Bridge/HuggingFace/ResponseConverter.php
  src/Bridge/OpenAI/DallE/ModelClient.php
  src/Bridge/TransformersPHP/Handler.php
  src/Bridge/TransformersPHP/PipelineResponse.php
  src/Bridge/TransformersPHP/PlatformFactory.php
  src/Chain/JsonSchema/Factory.php
  src/Chain/Toolbox/Tool/Crawler.php
  src/Model/Message/Content/File.php
  src/Model/Response/BinaryResponse.php
Labels: refactor
