Repository php-llm/llm-chain, pull requests merged in 2025-03, with the labels that each got.

#237 ci: add PR validation and auto labeling
  .github/workflows/pipeline.yml
Labels: CI/CD

#239 refactor: rename tool param attribute
  README.md
  src/Chain/ToolBox/Attribute/With.php
  src/Chain/ToolBox/ParameterAnalyzer.php
  src/Chain/ToolBox/Tool/OpenMeteo.php
  tests/Chain/ToolBox/Attribute/ToolParameterTest.php
  tests/Chain/ToolBox/ParameterAnalyzerTest.php
  tests/Fixture/Tool/ToolWithToolParameterAttribute.php
Labels: BC BREAK, refactor

#240 docs: better readability
  README.md
Labels: documentation

#242 docs: fix syntax
  README.md
Labels: documentation

#241 chore: reorganize makefile
  Makefile
  README.md
Labels: chore

#238 docs: add contributing file
  CONTRIBUTING.md
  README.md
Labels: documentation

#245 docs: fix make in contrib
  CONTRIBUTING.md
Labels: documentation

#244 chore: disable memory limit for phpstan
  Makefile
Labels: chore

#212 refactor: centralize json schema generation
  README.md
  composer.json
  src/Chain/JsonSchema/Attribute/With.php
  src/Chain/JsonSchema/DescriptionParser.php
  src/Chain/JsonSchema/Factory.php
  src/Chain/StructuredOutput/ResponseFormatFactory.php
  src/Chain/StructuredOutput/SchemaFactory.php
  src/Chain/ToolBox/Metadata.php
  src/Chain/ToolBox/ParameterAnalyzer.php
  src/Chain/ToolBox/Tool/OpenMeteo.php
  src/Chain/ToolBox/ToolAnalyzer.php
  tests/Chain/JsonSchema/DescriptionParserTest.php
  tests/Chain/JsonSchema/FactoryTest.php
  tests/Chain/StructuredOutput/ResponseFormatFactoryTest.php
  tests/Chain/StructuredOutput/SchemaFactoryTest.php
  tests/Chain/ToolBox/Attribute/ToolParameterTest.php
  tests/Chain/ToolBox/ToolAnalyzerTest.php
  tests/Chain/ToolBox/ToolBoxTest.php
  tests/Fixture/StructuredOutput/UserWithConstructor.php
  tests/Fixture/Tool/ToolArray.php
  tests/Fixture/Tool/ToolWithToolParameterAttribute.php
  tests/Fixture/Tool/ToolWithoutDocs.php
Labels: refactor

#243 feat: support multiple urls in Tavily tool
  src/Chain/ToolBox/Tool/Tavily.php
Labels: feature

#246 ci: use `bug` instead of `fix` label
  .github/workflows/pipeline.yml
Labels: CI/CD

#248 refactor: ease toolbox instatiation
  README.md
  examples/store-mongodb-similarity-search.php
  examples/store-pinecone-similarity-search.php
  examples/stream-tools-gpt-openai.php
  examples/structured-output-clock.php
  examples/toolbox-clock.php
  examples/toolbox-serpapi.php
  examples/toolbox-tavily.php
  examples/toolbox-weather-event.php
  examples/toolbox-wikipedia.php
  examples/toolbox-youtube.php
  src/Chain/ToolBox/Tool/Clock.php
  src/Chain/ToolBox/ToolBox.php
Labels: refactor

#250 feat: extend Audio content for data urls and raw data
  README.md
  examples/audio-describer.php
  src/Model/Message/Content/Audio.php
  tests/Model/Message/Content/AudioTest.php
  tests/Model/Message/UserMessageTest.php
Labels: BC BREAK, feature

#251 feat: add support for whisper on openai
  README.md
  examples/audio-transcript-whisper.php
  src/Bridge/OpenAI/PlatformFactory.php
  src/Bridge/OpenAI/Whisper.php
  src/Bridge/OpenAI/Whisper/File.php
  src/Bridge/OpenAI/Whisper/ModelClient.php
Labels: feature

#249 refactor: introduce tool metadata factory interface
  src/Chain/ToolBox/Exception/ToolConfigurationException.php
  src/Chain/ToolBox/MetadataFactory.php
  src/Chain/ToolBox/MetadataFactory/ReflectionFactory.php
  src/Chain/ToolBox/ToolBox.php
  tests/Chain/ToolBox/MetadataFactory/ReflectionFactoryTest.php
  tests/Chain/ToolBox/ToolBoxTest.php
Labels: refactor

#254 fix: handle void|null tool response graceful
  src/Chain/ToolBox/ToolResultConverter.php
  tests/Chain/ToolBox/ToolResultConverterTest.php
Labels: bug, BC BREAK

#253 fix: remove +x on example files
  examples/audio-describer.php
  examples/audio-transcript-whisper.php
  examples/chat-claude-anthropic.php
  examples/chat-gpt-azure.php
  examples/chat-gpt-openai.php
  examples/chat-llama-ollama.php
  examples/chat-llama-replicate.php
  examples/chat-o1-openai.php
  examples/chat-system-prompt.php
  examples/embeddings-openai.php
  examples/embeddings-voyage.php
  examples/image-describer-binary-gemini.php
  examples/image-describer-binary.php
  examples/image-describer-url.php
  examples/store-mongodb-similarity-search.php
  examples/store-pinecone-similarity-search.php
  examples/structured-output-clock.php
  examples/toolbox-clock.php
  examples/toolbox-serpapi.php
  examples/toolbox-tavily.php
  examples/toolbox-weather-event.php
  examples/toolbox-wikipedia.php
  examples/toolbox-youtube.php
Labels: bug

#257 test: fix coverage again
  tests/Chain/InputProcessor/SystemPromptInputProcessorTest.php
  tests/Chain/ToolBox/ChainProcessorTest.php
Labels: test

#252 feat: add whisper azure support
  README.md
  src/Bridge/Azure/OpenAI/PlatformFactory.php
  src/Bridge/Azure/OpenAI/WhisperModelClient.php
  src/Bridge/OpenAI/PlatformFactory.php
  src/Bridge/OpenAI/Whisper/ModelClient.php
  src/Bridge/OpenAI/Whisper/ResponseConverter.php
Labels: feature

#259 feat: support stringable system prompt
  src/Chain/InputProcessor/SystemPromptInputProcessor.php
  tests/Chain/InputProcessor/SystemPromptInputProcessorTest.php
  tests/Chain/InputProcessor/SystemPromptService.php
Labels: feature

#260 refactor: introduce execution reference in tool metadata
  src/Chain/ToolBox/Exception/ToolNotFoundException.php
  src/Chain/ToolBox/ExecutionReference.php
  src/Chain/ToolBox/Metadata.php
  src/Chain/ToolBox/MetadataFactory/ReflectionFactory.php
  src/Chain/ToolBox/ToolBox.php
  tests/Chain/InputProcessor/SystemPromptInputProcessorTest.php
  tests/Chain/ToolBox/ChainProcessorTest.php
  tests/Chain/ToolBox/FaultTolerantToolBoxTest.php
  tests/Chain/ToolBox/MetadataFactory/ReflectionFactoryTest.php
Labels: refactor

#256 feat: introduce chain and memory tool metadata factory
  src/Chain/ToolBox/Exception/ToolConfigurationException.php
  src/Chain/ToolBox/Exception/ToolMetadataException.php
  src/Chain/ToolBox/MetadataFactory.php
  src/Chain/ToolBox/MetadataFactory/AbstractFactory.php
  src/Chain/ToolBox/MetadataFactory/ChainFactory.php
  src/Chain/ToolBox/MetadataFactory/MemoryFactory.php
  src/Chain/ToolBox/MetadataFactory/ReflectionFactory.php
  tests/Chain/InputProcessor/SystemPromptInputProcessorTest.php
  tests/Chain/ToolBox/MetadataFactory/ChainFactoryTest.php
  tests/Chain/ToolBox/MetadataFactory/MemoryFactoryTest.php
  tests/Chain/ToolBox/MetadataFactory/ReflectionFactoryTest.php
  tests/Chain/ToolBox/ToolBoxTest.php
  tests/Fixture/Tool/ToolNoAttribute1.php
  tests/Fixture/Tool/ToolNoAttribute2.php
Labels: BC BREAK, feature

#261 test: fix namespaces and coverage usage
  tests/Chain/InputProcessor/SystemPromptInputProcessorTest.php
  tests/Chain/JsonSchema/Attribute/ToolParameterTest.php
  tests/Chain/Toolbox/ChainProcessorTest.php
  tests/Chain/Toolbox/FaultTolerantToolboxTest.php
  tests/Chain/Toolbox/MetadataFactory/ChainFactoryTest.php
  tests/Chain/Toolbox/MetadataFactory/MemoryFactoryTest.php
  tests/Chain/Toolbox/MetadataFactory/ReflectionFactoryTest.php
  tests/Chain/Toolbox/Tool/OpenMeteoTest.php
  tests/Chain/Toolbox/Tool/WikipediaTest.php
  tests/Chain/Toolbox/Tool/fixtures/openmeteo-current.json
  tests/Chain/Toolbox/Tool/fixtures/openmeteo-forecast.json
  tests/Chain/Toolbox/Tool/fixtures/wikipedia-article-missing.json
  tests/Chain/Toolbox/Tool/fixtures/wikipedia-article-redirect.json
  tests/Chain/Toolbox/Tool/fixtures/wikipedia-article.json
  tests/Chain/Toolbox/Tool/fixtures/wikipedia-search-empty.json
  tests/Chain/Toolbox/Tool/fixtures/wikipedia-search-result.json
  tests/Chain/Toolbox/ToolboxTest.php
Labels: test

#263 feat: support date time tool results
  examples/toolbox-clock.php
  src/Chain/Toolbox/ToolResultConverter.php
  tests/Chain/Toolbox/ToolResultConverterTest.php
Labels: feature

#262 docs: add section about different tool metadata factories
  README.md
Labels: documentation

#265 fix: exception message in ToolMetadataException
  src/Chain/Toolbox/Exception/ToolMetadataException.php
  tests/Chain/Toolbox/MetadataFactory/ChainFactoryTest.php
  tests/Chain/Toolbox/MetadataFactory/MemoryFactoryTest.php
  tests/Chain/Toolbox/MetadataFactory/ReflectionFactoryTest.php
Labels: bug

#267 fix: complex json schema default
  src/Chain/JsonSchema/Factory.php
Labels: bug

#266 feat: add chain wrapper tool
  src/Chain/Toolbox/Tool/Chain.php
Labels: feature
