Repository php-llm/llm-chain, pull requests merged in 2025-07, with the labels that each got.

#375 refactor: remove resolver interface for now
  src/Chain/Toolbox/ToolCallArgumentResolver.php
  src/Chain/Toolbox/ToolCallArgumentResolverInterface.php
  src/Chain/Toolbox/Toolbox.php
  tests/Chain/Toolbox/ToolCallArgumentResolverTest.php
Labels: refactor

#372 feat: open contract for more flexible normalizer configuration
  src/Platform/Bridge/Anthropic/Contract/AnthropicContract.php
  src/Platform/Bridge/Anthropic/PlatformFactory.php
  src/Platform/Bridge/Azure/Meta/PlatformFactory.php
  src/Platform/Bridge/Azure/OpenAI/PlatformFactory.php
  src/Platform/Bridge/Bedrock/PlatformFactory.php
  src/Platform/Bridge/Google/Contract/GoogleContract.php
  src/Platform/Bridge/Google/PlatformFactory.php
  src/Platform/Bridge/HuggingFace/PlatformFactory.php
  src/Platform/Bridge/Mistral/PlatformFactory.php
  src/Platform/Bridge/Ollama/PlatformFactory.php
  src/Platform/Bridge/OpenAI/PlatformFactory.php
  src/Platform/Bridge/OpenRouter/PlatformFactory.php
  src/Platform/Bridge/Replicate/PlatformFactory.php
  src/Platform/Bridge/Voyage/PlatformFactory.php
  src/Platform/Contract.php
Labels: enhancement

#376 refactor!: improve types in platform api
  README.md
  examples/azure/audio-transcript.php
  examples/azure/embeddings.php
  examples/huggingface/audio-classification.php
  examples/huggingface/automatic-speech-recognition.php
  examples/huggingface/chat-completion.php
  examples/huggingface/feature-extraction.php
  examples/huggingface/fill-mask.php
  examples/huggingface/image-classification.php
  examples/huggingface/image-segmentation.php
  examples/huggingface/image-to-text.php
  examples/huggingface/object-detection.php
  examples/huggingface/question-answering.php
  examples/huggingface/sentence-similarity.php
  examples/huggingface/summarization.php
  examples/huggingface/table-question-answering.php
  examples/huggingface/text-classification.php
  examples/huggingface/text-generation.php
  examples/huggingface/text-to-image.php
  examples/huggingface/token-classification.php
  examples/huggingface/translation.php
  examples/huggingface/zero-shot-classification.php
  examples/mistral/embeddings.php
  examples/openai/audio-transcript.php
  examples/openai/embeddings.php
  examples/openai/image-output-dall-e-2.php
  examples/openai/image-output-dall-e-3.php
  examples/parallel-chat-gpt.php
  examples/parallel-embeddings.php
  examples/transformers/text-generation.php
  examples/voyage/embeddings.php
  src/Chain/Chain.php
  src/Chain/Toolbox/Tool/SimilaritySearch.php
  src/Platform/Bridge/Bedrock/Anthropic/ClaudeHandler.php
  src/Platform/Bridge/Bedrock/BedrockModelClient.php
  src/Platform/Bridge/Bedrock/Meta/LlamaModelClient.php
  src/Platform/Bridge/Bedrock/Nova/NovaHandler.php
  src/Platform/Bridge/Bedrock/Platform.php
  src/Platform/Bridge/Bedrock/RawBedrockResponse.php
  src/Platform/Bridge/OpenAI/TokenOutputProcessor.php
  src/Platform/Bridge/TransformersPHP/PipelineExecution.php
  src/Platform/Bridge/TransformersPHP/Platform.php
  src/Platform/Bridge/TransformersPHP/RawPipelineResponse.php
  src/Platform/Contract.php
  src/Platform/Exception/UnexpectedResponseTypeException.php
  src/Platform/Platform.php
  src/Platform/PlatformInterface.php
  src/Platform/Response/AsyncResponse.php
  src/Platform/Response/BaseResponse.php
  src/Platform/Response/RawHttpResponse.php
  src/Platform/Response/RawResponseAwareTrait.php
  src/Platform/Response/RawResponseInterface.php
  src/Platform/Response/ResponseInterface.php
  src/Platform/Response/ResponsePromise.php
  src/Store/Document/Vectorizer.php
  tests/Platform/Bridge/OpenAI/TokenOutputProcessorTest.php
  tests/Platform/Response/BaseResponseTest.php
  tests/Platform/Response/RawResponseAwareTraitTest.php
  tests/Platform/Response/ResponsePromiseTest.php
  tests/Store/IndexerTest.php
Labels: BC BREAK, refactor

#384 feat: use intersection type `AbstractUid&TimeBasedUidInterface` for flexible message IDs
  src/Platform/Message/AssistantMessage.php
  src/Platform/Message/MessageInterface.php
  src/Platform/Message/SystemMessage.php
  src/Platform/Message/ToolCallMessage.php
  src/Platform/Message/UserMessage.php
  tests/Platform/ContractTest.php
  tests/Platform/Message/AssistantMessageTest.php
  tests/Platform/Message/SystemMessageTest.php
  tests/Platform/Message/ToolCallMessageTest.php
  tests/Platform/Message/UserMessageTest.php
Labels: BC BREAK

#390 chore!: PHP LLM becomes Symfony AI
  README.md
  composer.json
Labels: BC BREAK
